[package]
name = "vrc-get-litedb"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
ar = "0.9.0"
memmap2 = "0.9.3"
object = { version = "0.32.2", default-features = false, features = ["macho"] }
