version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/vrc-get-gui"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
