[package]
name = "vrc-get"
version = "0.1.2-SNAPSHOT"
edition = "2021"

license = "MIT"
authors = ["anatawa12 <anatawa12@icloud.com>"]
description = "Open Source command line client of VRChat Package Manager."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async_zip = { version = "0.0.11", features = ["deflate"] }
clap = { version = "4.1.3", features = ["derive"] }
env_logger = "0.10.0"
futures = "0.3.25"
indexmap = { version = "1.9.2", features = ["serde"] }
itertools = "0.10.5"
log = "0.4.17"
pin-project-lite = "0.2.9"
reqwest = { version = "0.11.14", features = ["blocking", "serde_json", "json", "native-tls-vendored"] }
semver = { version = "1.0.16", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive", "rc"] }
serde_json = { version = "1.0.91", features = ["preserve_order"] }
sha2 = "0.10.6"
tokio = { version = "1.24.2", features = ["rt", "macros", "fs"] }
uuid = { version = "1.2.2", features = ["v4"] }
