[package]
name = "vpm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async_zip = { version = "0.0.11", features = ["deflate"] }
clap = { version = "4.0.32", features = ["derive"] }
env_logger = "0.10.0"
futures = "0.3.25"
indexmap = { version = "1.9.2", features = ["serde"] }
log = "0.4.17"
reqwest = { version = "0.11.14", features = ["blocking", "serde_json", "json"] }
semver = { version = "1.0.16", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive", "rc"] }
serde_json = { version = "1.0.91", features = ["preserve_order"] }
tokio = { version = "1.24.2", features = ["rt", "macros", "fs"] }
