[workspace]
resolver = "2"

members = [
    "build-check-static-link",
    "vrc-get",
    "vrc-get-gui",
    "vrc-get-litedb",
    "vrc-get-vpm"
]

[workspace.package]
edition = "2021"

license = "MIT"
authors = ["anatawa12 <anatawa12@icloud.com>"]
homepage = "https://github.com/anatawa12/vrc-get#readme"
repository = "https://github.com/anatawa12/vrc-get"
readme = "README.md"
