name: "[vrc-get-gui] Feature Request"
description: Suggest an idea for vrc-get-gui / vrc-get-guiに新しい機能を提案する
labels: ["enhancement", "vrc-get-gui"]
projects: ["vrc-get/1"]

body:
  - type: textarea
    attributes:
      label: Summary / 概要
      description: |
        Please describe the suggestion. If it is related to the UI, some figures should help to image it.
        どんな提案ですか? UIに関するものであれば、図があると分かりやすいかもしれません。
    validations:
      required: true

  - type: textarea
    attributes:
      label: Purpose / 目的
      description: |
        What problems or needs do you think this feature will solve?
        その機能の追加によって、どんな問題やニーズが解決されそうですか?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context / 補足
      description: |
        Add any other context about the feature request here.
        補足したい内容があればここに書いて下さい。
