[build]
beforeBuildCommand = "npm run build"
beforeDevCommand = "npm run dev"
devPath = "http://localhost:3000"
distDir = "out"

[package]
productName = "vrc-get-gui"

[tauri]

[tauri.allowlist]
shell = { open = "^(https?://\\w+).+" }

[tauri.security]
# csp = 

[tauri.updater]
active = false

[[tauri.windows]]
title = "vrc-get-gui"
url = "/projects"

fullscreen = false
resizable = true
height = 800
width = 1000

[tauri.bundle]
active = true
targets = [
    "appimage",
    "nsis", #-setup.exe
    "app", # needs for dmg
    "dmg",
]
longDescription = "vrc-get-gui is a fast and open-source alternative VCC (VRChat Creator Companion) written in rust and tauri."
shortDescription = "an alternative VCC"
identifier = "com.anataw12.vrc-get"
category = "DeveloperTool"
copyright = "(c) anatawa12 and other contributors"

externalBin = []
icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico",
]
resources = []

[tauri.bundle.deb]
depends = []

[tauri.bundle.macOS]
exceptionDomain = ""
frameworks = []
providerShortName = "anatawa12"

[tauri.bundle.windows]
digestAlgorithm = "sha256"
