[target.'cfg(all(target_os = "linux", not(proc_macro)))']
rustflags = ["-C", "target-feature=+crt-static"]

[target.'cfg(all(windows, target_env = "msvc", not(proc_macro)))']
rustflags = ["-C", "target-feature=+crt-static"]
