[package]
name = "vrc-get-vpm"

# discreate versioning since this library will not have stable versions
version = "0.0.1"

edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

description = "Open Source client of VRChat Package Manager. This is the library is made for vrc-get."
readme = "README.md"
keywords = ["vpm", "package-manager"]
categories = ["command-line-utilities"]

[dependencies]
async_zip = { version = "0.0.15", features = ["deflate", "tokio", "deflate64"] }
futures = "0.3.29"
indexmap = { version = "2.1.0", features = ["serde"] }
itertools = "0.12.0"
log = "0.4.20"
pin-project-lite = "0.2.13"
reqwest = { version = "0.11.22", features = ["stream"], default-features = false }
serde = { version = "1.0.193", features = ["derive", "rc"] }
serde_json = { version = "1.0.108", features = ["preserve_order"] }
sha2 = "0.10.8"
tokio = { version = "1.35.0", features = ["fs"] }
tokio-util = "0.7.10"
uuid = { version = "1.6.1", features = ["v4"] }

[target."cfg(windows)".dependencies]
windows = { version = "0.52.0", features = ["Win32_UI_Shell", "Win32_Foundation", "Win32_System_Com"] }

[features]
default = ["rustls"]
native-tls = ["reqwest/native-tls-vendored"]
rustls = ["reqwest/rustls-tls-native-roots"]
