name: CI (Build)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # for linux, use cross on ubuntu-latest
          - triple: x86_64-unknown-linux-musl
            run-test: true
            on: ubuntu-latest
            setup: |
              sudo apt update && sudo apt install -y lld
              sudo ln -s "/usr/bin/ld.lld" /usr/local/x86_64-linux-musl/bin/ld.lld
              /usr/local/x86_64-linux-musl/bin/ld.lld --version
            rustflags: "-C link-arg=-fuse-ld=lld -C target-feature=+crt-static"
          - triple: aarch64-unknown-linux-musl
            run-test: true
            on: ubuntu-latest
            setup: |
              sudo apt update && sudo apt install -y lld
              sudo ln -s "/usr/bin/ld.lld" /usr/local/aarch64-linux-musl/bin/ld.lld
              /usr/local/aarch64-linux-musl/bin/ld.lld --version
            rustflags: "-C link-arg=-fuse-ld=lld -C default-linker-libraries=y -C target-feature=+crt-static"
          # linux with gnu toolchain
          - triple: x86_64-unknown-linux-gnu
            run-test: true
            on: ubuntu-latest
            setup: |
              sudo apt update && sudo apt install -y lld
              sudo ln -s "/usr/bin/ld.lld" /usr/local/aarch64-linux-musl/bin/ld.lld
              /usr/local/aarch64-linux-musl/bin/ld.lld --version
            rustflags: "-C link-arg=-fuse-ld=lld"
          - triple: aarch64-unknown-linux-gnu
            run-test: true
            on: ubuntu-latest
            setup: |
              sudo apt update && sudo apt install -y lld
              ld.lld --version
            rustflags: "-C link-arg=-fuse-ld=lld"
          # for windows, use cross on ubuntu-latest
          - triple: x86_64-pc-windows-msvc
            run-test: true
            on: windows-latest
          #- triple: aarch64-pc-windows-msvc
          #  on: macos-latest
          #  cross: false
          # for macOS, on macOS without cross
          - triple: x86_64-apple-darwin
            run-test: true
            on: macos-latest
          - triple: aarch64-apple-darwin
            run-test: false
            on: macos-latest
        triple:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-pc-windows-msvc
          #- aarch64-pc-windows-msvc
          - x86_64-apple-darwin
          - aarch64-apple-darwin

    runs-on: ${{ matrix.on }}
    env:
      RUSTFLAGS: ${{ matrix.rustflags }} -C link-arg=-Wl,--verbose
      RUSTC_LOG: rustc_codegen_ssa::back::link=info

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.triple }}
      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.triple }}
      - uses: Swatinem/rust-cache@v1
        with:
          target-dir: target
          key: ci-build

      - name: Setup
        run: ${{ matrix.setup }}
      - name: Build
        run: cargo build --verbose --target ${{ matrix.triple }}
      - name: Upload built binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.triple }}
          path: |
            target/${{ matrix.triple }}/debug/vrc-get*
            target/${{ matrix.triple }}/debug/libvrc-get*
      - name: Build tests
        run: cargo build --tests --target ${{ matrix.triple }}
      - name: Run tests
        if: ${{ matrix.run-test }}
        run: cargo test --verbose --target ${{ matrix.triple }}
