name: CI (Build)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            target: x86_64-unknown-linux-musl
            setup: sudo apt update && sudo apt install -y musl-tools binutils
          - runs-on: windows-latest
            target: x86_64-pc-windows-msvc
        runs-on:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v1
        with:
          target-dir: target
          key: ci-build
      - name: Setup
        run: ${{ matrix.setup }}
      - name: Build
        run: cargo build --verbose --target ${{ matrix.target }}
      - name: Run tests
        run: cargo test --verbose --target ${{ matrix.target }}
