name: CI (Build)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # for linux, use cross on ubuntu-latest
          - triple: x86_64-unknown-linux-musl
            run-test: true
            on: ubuntu-latest
            setup: sudo apt update && sudo apt install -y musl-tools lld
            rustflags: "-C link-arg=-fuse-ld=lld"
          - triple: aarch64-unknown-linux-musl
            run-test: false
            on: ubuntu-latest
            setup: |
              # setup musl tools for cross compilation 

              # setup env settings
              sudo dpkg --add-architecture arm64
              sudo apt update || true

              # install cross compiler
              sudo apt install -y gcc-11-aarch64-linux-gnu lld
              # setup musl tools
              NEW_ARCH=aarch64-linux-musl
              mkdir .setup-musl
              pushd .setup-musl
              apt download musl-dev:arm64
              dpkg --extract musl-dev*.deb musl-dev
              ln -s musl-dev/usr/include/$NEW_ARCH /usr/include/$NEW_ARCH
              ln -s musl-dev/usr/lib/$NEW_ARCH /usr/lib/$NEW_ARCH
              sudo tee /usr/bin/x86_64-linux-musl-gcc << 'EOF'
              #!/bin/sh
              exec "${REALGCC:-aarch64-linux-gnu-gcc}" "$@" -specs "/usr/lib/aarch64-linux-musl/musl-gcc.specs"
              EOF
              popd
            rustflags: "-C link-arg=-fuse-ld=lld -C linker=x86_64-linux-musl-gcc -C linker-flavor=gcc"
          # for windows, use cross on ubuntu-latest
          - triple: x86_64-pc-windows-msvc
            run-test: true
            on: windows-latest
          #- triple: aarch64-pc-windows-msvc
          #  on: macos-latest
          #  cross: false
          # for macOS, on macOS without cross
          - triple: x86_64-apple-darwin
            run-test: true
            on: macos-latest
          - triple: aarch64-apple-darwin
            run-test: false
            on: macos-latest
        triple:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - x86_64-pc-windows-msvc
          #- aarch64-pc-windows-msvc
          - x86_64-apple-darwin
          - aarch64-apple-darwin

    runs-on: ${{ matrix.on }}
    env:
      RUSTFLAGS: ${{ matrix.rustflags }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.triple }}
      - uses: Swatinem/rust-cache@v1
        with:
          target-dir: target
          key: ci-build
      - name: Setup
        run: ${{ matrix.setup }}
      - name: Build
        run: cargo build --verbose --target ${{ matrix.triple }}
      - name: Build tests
        if: ${{ matrix.run-test }}
        run: cargo build --tests --target ${{ matrix.triple }}
      - name: Run tests
        run: cargo test --verbose --target ${{ matrix.triple }}
